### ISSUE TITLE
how to run the project?

### ISSUE THREAD

**Issue by Ixiaohuihuihui** [jmrf/HOG-Pedestrian-Detector#1]
Dear author:
I have a problem, how to run the project? which script is  the entry point to the project?

**Comment by josemarcosrf** [comment]
Hi, 

As I remember you should be able to train the model running `train_svm.m` or `train_svm_pca.m`

This should produce models that afterwards can be tested by `test_svm.m` or `test_svm_pca.m`.

You should also be able to see the detector performing real searches on whole images running `sliding_detector.m`

This was a project I did for my thesis long time ago so is a bit rusted in my memory, but let me know if you manage to get it running or I can help you somehow.

**Comment by ichang1995** [comment]
Dear jmrf,

Could you please confirm the folder has included all your files to implement the detection process cause I cannot find the main script to run the code and I don't know the order of every function you provided.  If you have the demo script, please upload if possible. Thanks.

**Comment by josemarcosrf** [comment]
Hi @ichang1995 ,

All files are present. Please remember that for the project to run, the `libs` directory and all its subdirectories should be in your MATLAB path. This will allow MATLAB to find all the helper routines and functions.

**Comment by rahuls321** [comment]
where are these folders--  model folder, positive image and negative image folder?? As when I am running  train_svm.m it needs these folders how to get it??

**Comment by ichang1995** [comment]
Thank you,jmrf. By the way, there is an error existing when I run the train_svm.m.  [model_save_path,filesep,model_name]); how can I define the parameter 'model_name'?

**Comment by ichang1995** [comment]
On the other hand, have you considered the use of hard examples, cause I haven't found where you have used two times of svm training. Looking forwards to your reply, thank you. Please provide a main.m script to run the functions you listed if it is convenient to you.

**Comment by ichang1995** [comment]
Dear jmrf,
Thank you for your reply. Could you please confirm which version of libsvm you used for training and testing. Because when I use the latest version of the libs, the model cannot be read unfortunately:' Error: can't read model: number of return field is not correct'  Thank you very much, looking forward to your reply.

**Comment by josemarcosrf** [comment]
@rahuls321 those folders you mentioned are arbitrary folders. Could be any directory you chose where to save your trained models, where to find positive images and negative images respectively.

**Comment by josemarcosrf** [comment]
Actually...

When I uploaded this project to github was mainly for me to store it somewhere. Was not expecting all this popularity...

So, given that apparently there's a bit of interest in it, I'll write a proper README explaining how to run the project.

**Comment by rahuls321** [comment]
Could you please update it soon? I'm working on it. @jmrf

**Comment by josemarcosrf** [comment]
@rahuls321 don't expect to see it any time soon as I am quite busy at the moment.

Nevertheless should be pretty straightforward to run a training at the very least as I know some other users that have been able to do so.

A good starting point would be to read section 6 of the thesis:
https://upcommons.upc.edu/bitstream/handle/2099.1/21343/95066.pdf?sequence=1&isAllowed=y
`6. IMPLEMENTATION AND USAGE`

Btw, how did you come to find my project?

**Comment by rahuls321** [comment]
I am getting this error whenever I run the program file "train_svm.m"

Struct contents reference from a non-struct array object.

Error in get_feature_matrix (line 44)
       I = imread(positive_images(i).name);

Error in train_svm (line 45)
    [labels, train_matrix]= get_feature_matrix(positive_images,negative_images);

**Comment by ichang1995** [comment]
@rahuls321 The author has updated the code which is adaptive to MATLAB 2018a and libsvm3.22, I have tested the training and testing functions and they both work. You can have another trial with the new source code. Many thanks to dear jrmf!! I am now learning his code, if you're doing the same thing, we can have a further interaction.

**Comment by rahuls321** [comment]
@ichang1995  Still, I am facing problems. Can you please fix this error? I am getting this error 

```
Undefined function or variable 'rdir'.

Error in get_files (line 39)
        positive_images = [positive_images; rdir(wildcard)];

Error in train_svm (line 44)
        get_files(pos, negs,{positive_images_path,negative_images_path});
```

**Comment by josemarcosrf** [comment]
@rahuls321 did you read how to run it?

**Comment by josemarcosrf** [comment]
@ichang1995 I am very happy to know it is now working for you.

**Comment by ichang1995** [comment]
I got this error yesterday, and it disappeared after re-opening the MATLAB.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rahuls321** [comment]
@jmrf yes I did but still, I am having problems. What I did, after running train_svm.m, I choose models first as you have said then I choose datasets folder and I made pos and negs two folder there by myself and choose after that But I am getting mentioned error after running. Please help me !!!!

**Comment by josemarcosrf** [comment]
@rahuls321 Looks like the `libs` directory is not part of your MATLAB path.

That's where the `rdir` and other auxiliary functions are.

Remember **all** sub-directories should also be included.

**Comment by ichang1995** [comment]
I’ll try to realize the rest of functions and get the results you mentioned in your thesis. Thank you very very much!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by josemarcosrf** [comment]
You are welcome!

Good luck with the experiments @ichang1995. Let me know if anything else gets you stuck.

It is likely you find other pieces of code not working due to MATLAB changes in functions, if so and you feel you know how to fix, please submit a PR and I'll introduce fixes.

**Comment by josemarcosrf** [comment]
Closing as few people now has been able to run successfully the project.

Any particular problems please open another github issue detailing what have been tried and what error messages are you getting

**Comment by irfan29641** [comment]
Nice Code 💯 but little Q why model is undetected even present in workspace.
E:\code4\others\HOG-Pedestrian-Detector-master\dataset\Test\pos\I00000.png
Not enough input arguments.

Error in sliding_detector (line 29)
        draw_sliding_window(I,model);
Or how to load properly model. Please reply soon if possible im working on it.
