### ISSUE TITLE
How to train on caltech dataset? 

### ISSUE THREAD

**Issue by zyfewq** [jmrf/HOG-Pedestrian-Detector#10]
How to train on caltech dataset?

**Comment by josemarcosrf** [comment]
Hey @zyfewq, 

Can you be a little more specific? What have you tried? What are you finding difficult to understand?

**Comment by lukas7fh** [comment]
Do you have the code for the star visual HOG feature? thank you

**Comment by jmrf** [comment]
> Do you have the code for the star visual HOG feature? thank you

I don't, I was not even aware of its existence.
