### ISSUE TITLE
 Sliding detector.m   line 29 draw_sliding_window(I,model); ( Even model is loaded in workspace)

### ISSUE THREAD

**Issue by irfan29641** [jmrf/HOG-Pedestrian-Detector#2]
E:\code4\others\HOG-Pedestrian-Detector-master\dataset\Test\pos\I00000.png
Not enough input arguments.

Error in sliding_detector (line 29)
        draw_sliding_window(I,model)

Thanks in advance!!!

**Comment by josemarcosrf** [comment]
Hi @irfan29641, 

Could you paste here how your call to the function looks like?

And also how the input variables are?

**Comment by irfan29641** [comment]
After two step
1.  model = train_svm("test", ["./models", "dataset/Train/pos" "dataset/Train/neg"]);  => generates test.mat and test.cv
2.  test_svm(model.test, ["dataset/Test/pos" "dataset/Test/neg"]);   => generates model.mat (i'm saving it through matlab home button save work space.

When model exist in workspace through passing these two step then error comes that pasted above (18 hours ago(Not enough input arguments).

If is add my manual save model.mat( though save button-as told in 2.step) like this in sliding detector
%% FILENAME  : sliding_detector.m 

    load('E:\code4\others\HOG-Pedestrian-Detector-master\models\model.mat')    % This one is addition  
    
    path = uigetdir('.\images','Select positive test image path');
    if isa(path,'double')

Then program stats to go through each pos image of test (and also going in draw_sliding_window)
with common error for each image in line = 3 below

begining the pyramid hog extraction...
time to extract 158 hogs: 4.026352e+00
Error: can't read model: number of return field is not correct
E:\code4\others\HOG-Pedestrian-Detector-master\dataset\Test\pos\I00287.png

**Comment by irfan29641** [comment]
Sir you know better then me but I guess i'm getting error in generating  model properly.

**Comment by Mahmood8136** [comment]
Hello jmrf
Me to getting same is
it train with two commands
```matlab
[model, Ureduce] = train_svm_PCA("test_pca", ["./models", "dataset/Train/pos" "dataset/Train/neg"]);
test_svm_PCA(model.test_pca, Ureduce, ["dataset/Test/pos", "dataset/Test/neg"]);
``` 
as irfan29641 told

in Sliding detector i made little change

%% FILENAME  : sliding_detector.m 

    **model = load('D:\1A\HOG-Pedestrian-Detector-master\models\test_pca_reduced_SVs.mat')
    OR 
        model = load('D:\1A\HOG-Pedestrian-Detector-master\models\test_pca.mat**
    path = uigetdir('.\images','Select positive test image path');
    if isa(path,'double')
        cprintf('Errors','Invalid paths...\nexiting...\n\n')
        return 
    end
**Error**
>> sliding_detector

model = 

  struct with fields:

    Ureduce: [3780×683 double]

D:\1A\HOG-Pedestrian-Detector-master\dataset\test\pos\I00000.png

begining the pyramid hog extraction...
time to extract 228 hogs: 3.517339e+00

**Error: can't read model: number of return field is not correct** (Cycle starts for each image)

All other program same as available online  
Kindly solve this issue (im using 2017b and libsvm-322 as you recommended) Thanks in advance!!!

**Comment by josemarcosrf** [comment]
Hey @irfan29641, @Mahmood8136 

Would you guys mind uploading the saved `struct` model and paste the link somewhere I can download it.

If I were to see the file itself maybe I can help.
I believe the error comes from the way the model is being saved/loaded...

If I get your model files I can check running it on my machine.

**Comment by Mahmood8136** [comment]
My models folder data
https://drive.google.com/open?id=1jspqJGrHRZ0oo2p0wsiNSn0gn4bBMUpa

I used to load these files as above
**model = load('D:\1A\HOG-Pedestrian-Detector-master\models\test_pca_reduced_SVs.mat')
OR 
    model = load('D:\1A\HOG-Pedestrian-Detector-master\models\test_pca.mat**

more precise error at draw_sliding_window.m line 80
[predict_labels, ~, probs] = ...
    svmpredict(zeros(size(hogs,1),1), hogs, model, '-b 1');

**Comment by irfan29641** [comment]
My whole folder here you can try whole or just take model

https://drive.google.com/open?id=1bXPUO9GDJ82AfxxQ0HQvzyY0GpwSJFnS

just change in sliding_detector.m (to call model)

you are seem right Sir "error comes from the way the model is being saved/loaded"

**Comment by Mahmood8136** [comment]
Dear jmrf kindly have a look, as soon as possible!!

**Comment by josemarcosrf** [comment]
@Mahmood8136 @irfan29641 

These steps work well for me:
1. downloaded [this model](https://drive.google.com/open?id=16VNfRyKmSOvTlTl3Glm9Ezv49mWXDLqM) from @Mahmood8136 GDrive folder

2. Cloned the master branch of the repo

3. Run: ```load('model.mat')```

4. Run: ```sliding_detector(model.test)``` -->  shows the sliding window

This is a screenshot of the results achieved with the `static_detector`:
![static_results](https://user-images.githubusercontent.com/10252518/51676957-d3ea6500-1fe0-11e9-9193-cd006c9d5163.jpg)

**Comment by josemarcosrf** [comment]
Just to be clear, and as stated in the `README` in the root of the repo.

You should pass the models to the functions as `model.<name you gave at training>`.

As per your comments above on the trainig procedure: `model.test`

Inspecting the resulting struct from **your** model,  shows as expected:
```
>> model

model = 

  struct with fields:

    test: [1×1 struct]
```

And the `svm` model inside, which was called `test`:
```
>> model.test

ans = 

  struct with fields:

    Parameters: [5×1 double]
      nr_class: 2
       totalSV: 958
           rho: -4.5209
         Label: [2×1 double]
    sv_indices: [958×1 double]
         ProbA: -0.6999
         ProbB: 0.2984
           nSV: [2×1 double]
       sv_coef: [958×1 double]
           SVs: [958×3780 double]
```

So using `model.test` in the inference functions works well.

@Mahmood8136 @irfan29641 please let me know if this solved it so I can close the issue.
Otherwise, let me know what other problems you are facing and maybe I can help further.

**Comment by Mahmood8136** [comment]
Thanks You so much Dear jmrf, God bless you!!! It help as you described by running in command window sliding_detector(model.test) and static_detector also!!! **work Fine**

**Comment by Mahmood8136** [comment]
I read you thesis, great explanation But im finding accuracy issues as you also seen above posed result pics (approx 4 human) can 
![image](https://user-images.githubusercontent.com/46928273/51752756-12177f80-20da-11e9-98b5-9aa3a367c924.png)

**Comment by josemarcosrf** [comment]
@Mahmood8136 glad to hear it worked.

I am closing the issue as it seems solved.

Regarding your last comment. Please see section `5.3 The final detector` of the thesis. Especially the *non-maximal-suppression* part.

**Comment by irfan29641** [comment]
Thanks
