### ISSUE TITLE
Hey jmrf : I'm read you thesis part 5.3 (non maximum suppression) learnt how it works but still confuse about command in how to use it in matlab

### ISSUE THREAD

**Issue by Mahmood8136** [jmrf/HOG-Pedestrian-Detector#4]
Can you please explain with example (command if possible)

**Comment by Mahmood8136** [comment]
With static_detector it goes through non_maximum_suppresion, but why accuracy is not as much as in thesis 
![image](https://user-images.githubusercontent.com/46928273/51768452-30917100-2102-11e9-860d-2728d57d039c.png)
![image](https://user-images.githubusercontent.com/46928273/51768467-3b4c0600-2102-11e9-94bc-b855be0d4ba8.png)

**Comment by Innazobova** [comment]
I'm also doing same does it will perform better by going through rbf kernel. 
This thing available online?=> "A very simple interaction is needed to run any of the detectors as we provide a compiled version for every implemented one."

**Comment by josemarcosrf** [comment]
@Mahmood8136 is very difficult to understand without any further information why the accuracy can be different. (SVM Kernels, hyper-parameters, cross-validations, ....)
If you replicate the experiments as explained in the thesis you should get the same results or almost the same results.
I am afraid I cannot help you with this one any more than pointing you to the thesis where. I am happy to address small specific issues but the overall theory behind the project is out of the scope of the help I can provide at this time.

@Innazobova No, I don't have compiled versions. For a comparison of kernels, please refer to the thesis
