### ISSUE TITLE
Hello JMRF i need you help in "plot_DETcurve.m"

### ISSUE THREAD

**Issue by irfan29641** [jmrf/HOG-Pedestrian-Detector#5]
i have a model **test 1*1 struct**  but i'm having problem in plot_DETcurve can you specify me command how to use plot_DETcurve.m. {I already talked to you in issue 2, Brother you helped me lot in this work :) }

**Comment by irfan29641** [comment]
I trying to it as with this command
**plot_DETcurve("test", ["./models", "dataset/test/pos" "dataset/test/neg"]);**
but this errors comes
```
model file should be a struct array
Subscripted assignment dimension mismatch.

Error in plot_DETcurve>get_scores (line 133)
        p_scores(i-this_chunk+1:i,:) = scores(:,:);

Error in plot_DETcurve (line 39)
        [p_scores, n_scores] = get_scores(model,pos_path,neg_path);
```

**Comment by irfan29641** [comment]
if trained model is model.test or only test then what will be command to proper use it in DET curves

**Comment by josemarcosrf** [comment]
Hey @irfan29641, 

I have no access to MATLAB right now but I'll try a bit later on today and revert here with an answer.

**Comment by josemarcosrf** [comment]
Hey @irfan29641 

Talking a bit from memory here, but try this please:

```matlab
% load the 1x1 model struct you mention in your first comment
load('model.mat'); 
% pass to the function a row vector with all the models you want to test
% and a cell array with model names to label the plots
plot_DETcurve([model.test], {'test-model'});
```

This should plot a couple of things; a histogram with classification scores and a DET curve. 

Let me know how that goes.
