### ISSUE TITLE
Where are the annotations files used?

### ISSUE THREAD

**Issue by QuickLearner171998** [jmrf/HOG-Pedestrian-Detector#7]
Hi , I am training the model.
I wanted to know in which function do you use the annotations for the images. 
Thanks

**Comment by josemarcosrf** [comment]
Hi, 

The labels are implicit from the dataset folder structure.

See https://github.com/jmrf/HOG-Pedestrian-Detector/blob/master/train_svm.m#L20

**Comment by QuickLearner171998** [comment]
But it takes only images right.
So do you suggest to keep my labels(annotations file) and images in the same folder. And also what is the type of annotation files.

**Comment by josemarcosrf** [comment]
No annotation files are used. By folder structure I mean you need to have two distinct folders where you keep separately `positive` examples and `negative` examples.

From the link referenced in my previous comment, in the code you can see:

```matlab
        positive_images_path = uigetdir('dataset','Select positive image folder');
        negative_images_path = uigetdir('dataset','Select negative image folder');
```

The training uses two directories. `positive` and `negative`, so the labels are implicit based on where you read from.

**Comment by QuickLearner171998** [comment]
Actually the Dataset that you mention in ur thesis says INRIA dataset. That had images which had objects in some parts. Also the dataset had annotations.
So acc to you pos and neg images must have only  the objects. For ex. If i am detecting a pedestrian then the image should contain only the pedestrian and nothing else. Right??

**Comment by josemarcosrf** [comment]
Yes, the [INRIA person dataset](http://pascal.inrialpes.fr/data/human/) was used to train and test the detector.

The dataset has annotation corresponding to the Bounding Boxes were a person can be found but those annotations are **not** used as the dataset provides image windows were either no person can be found in it (`negative` set) or a person or more can be found (`positive` set).

This is explained in greater detail in the dataset page linked above.

The dataset contains a `Train` and a `Test` folder both with `pos` and `neg` sub-directories where you'll find the original images.
In addition there's also `train_64x128_H96` and `test_64x128_H96` where you have a image crops to use in a sliding window approach.

**Comment by AtharvT** [comment]
Hi. I have been trying to use the model for INRIA dataset but was unable to do so.
1. Where would the negative image folder for "\train_64x128_H96" be? When I downloaded the dataset, the cropped images folder did not have a neg folder. It had pos.lst and neg.lst. Is the dataset being read using this?
2. How and where are using the sliding window?

3. I have been getting null test results of the trained model. When I train it, the accuracy is not changing. 
TIA.

**Comment by josemarcosrf** [comment]
Hi @AtharvT 

1. Re the dataset:
In the `train_64x128_H96` directory, there is a folder called `pos` containing the image crops and a symlink called `neg` to the original *negative images*. Refer to the [INRIA dataset site](http://pascal.inrialpes.fr/data/human/) to understand it. Specially the `Original Images`, `Normalized Images` and `Negative windows` sections.

2. You'll find this explained in the [thesis](https://upcommons.upc.edu/bitstream/handle/2099.1/21343/95066.pdf?sequence=1&isAllowed=y). Check section `5. Pedestrian detection` to understand the sliding window mechanism.

3. I don't think I can help you much with this description.
