### ISSUE TITLE
test_svm can't  run on matlab2019b

### ISSUE THREAD

**Issue by littledour** [jmrf/HOG-Pedestrian-Detector#9]
test_svm('model_1')
错误: 文件: test_svm.m 行: 66 列: 25
The identifier 'pos_chunk_size' is not a function or shared variable. To share 'pos_chunk_size' with nested functions, initialize it in the current scope. For more information, see Sharing variables between parent functions and nested functions.
I have watched the video on youtube, but I don't understand how to run test_svm. does't it need a main.m?  @jmrf

**Comment by josemarcosrf** [comment]
Hi @coolrido, 

Not sure I understand properly the issue description. What video did you watch?

If you are encountering issues running `test_svm`, have you checked you environment is initialized as described in the section [setting-the-environment](https://github.com/jmrf/HOG-Pedestrian-Detector#setting-the-environment) from the `README`?

**Comment by littledour** [comment]
Hi, @jmrf 
the environment is ok, `train_svm`can run, but`test_svm`can't. I want know the running sequence of this program to confirm if I ignore some functions, here is the video. [https://www.youtube.com/watch?v=zzhh6M66iH0]

**Comment by josemarcosrf** [comment]
Hey @coolrido thanks for the video link. I'll watch it tomorrow and come back with what I spotted.

**Comment by josemarcosrf** [comment]
@coolrido I've checked the video and following that should work.

Could you paste here the stack-trace of what you are seeing when you run it?

Note that all of this was tested on Matlab `R2017b`. I presume it should just work fine on newer versions... but that's an assumption as I don't have Matlab to try it now.

**Comment by josemarcosrf** [comment]
Closing it as there's no new activity. Hope it is solved by now.
